package com.example.busbookingapp.data

import com.example.busbookingapp.models.AdminUser
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore

class AuthRepository {
    // Standard singleton instances for Firebase
    private val auth = FirebaseAuth.getInstance()
    private val db = FirebaseFirestore.getInstance()

    /**
     * Creates a login in Auth, then creates a profile in Firestore 'users' collection.
     */
    fun registerNewAdmin(admin: AdminUser, pass: String, onResult: (Boolean, String?) -> Unit) {
        auth.createUserWithEmailAndPassword(admin.email, pass)
            .addOnSuccessListener { authResult ->
                // 1. Get the Unique ID generated by Firebase Auth
                val uid = authResult.user?.uid ?: ""

                // 2. Attach that ID to your AdminUser object
                val finalizedAdmin = admin.copy(uid = uid)

                // 3. Save the object to Firestore using the UID as the Document ID
                db.collection("users").document(uid)
                    .set(finalizedAdmin)
                    .addOnSuccessListener {
                        onResult(true, null)
                    }
                    .addOnFailureListener { e ->
                        onResult(false, "Firestore Error: ${e.message}")
                    }
            }
            .addOnFailureListener { e ->
                onResult(false, "Auth Error: ${e.message}")
            }
    }

    /**
     * Standard login using Firebase Auth
     */
    fun login(email: String, pass: String, onResult: (Boolean, String?) -> Unit) {
        auth.signInWithEmailAndPassword(email, pass)
            .addOnSuccessListener {
                onResult(true, null)
            }
            .addOnFailureListener { e ->
                onResult(false, e.message)
            }
    }
}